update workflows

diff --git a/.github/workflows/semgrep-rules-test-historical.yml b/.github/workflows/semgrep-rules-test-historical.yml
--- a/.github/workflows/semgrep-rules-test-historical.yml
+++ b/.github/workflows/semgrep-rules-test-historical.yml
@@ -1,4 +1,4 @@
-name: semgrep-rules-test-historical
+name: opengrep-rules-test-historical
 on:
   pull_request:
     branches:
@@ -15,7 +15,7 @@ jobs:
     steps:
     - uses: actions/checkout@v2
       with:
-        path: semgrep-rules
+        path: opengrep-rules
         fetch-depth: 0
     - uses: actions/setup-python@v2
       with:
@@ -24,32 +24,33 @@ jobs:
       id: changed-files
       uses: tj-actions/changed-files@v41
       with:
-        path: semgrep-rules
+        path: opengrep-rules
         separator: ","
     # need to delete these directories or else we get linter errors during 
     # the "validate" step.
+    # TODO: deploy a pip for opengrep
     - name: install semgrep
       run: pip3 install semgrep
     - name: delete stats directory
-      run: rm -rf semgrep-rules/stats
+      run: rm -rf opengrep-rules/stats
     - name: delete rules requiring Semgrep Pro
-      run: rm -rf semgrep-rules/apex semgrep-rules/elixir
+      run: rm -rf opengrep-rules/apex opengrep-rules/elixir
     # TODO: remove this in the future, there was a regression in semgrep that
     # caused non-rule YAML files to be validated
     - name: delete YAML files that are not rules
       run: |
-        rm -f semgrep-rules/.pre-commit-config.yaml
-        rm -rf semgrep-rules/.github
+        rm -f opengrep-rules/.pre-commit-config.yaml
+        rm -rf opengrep-rules/.github
     - name: grab historical semgrep version
       env:
         GH_TOKEN: ${{ github.token }}
-      run: semgrep-rules/scripts/historical-semgrep-version
+      run: opengrep-rules/scripts/historical-semgrep-version
     - name: validate rules on historical semgrep version
       run: |
-        docker run --rm -v ${GITHUB_WORKSPACE}/semgrep-rules:/src returntocorp/semgrep:${SEMGREP_OLD_VERSION} semgrep --validate --config /src
+        docker run --rm -v ${GITHUB_WORKSPACE}/opengrep-rules:/src opengrep/opengrep:${SEMGREP_OLD_VERSION} semgrep --validate --config /src
     - name: test with historical semgrep version
       run: |
-        TESTSUITE_OUTPUT="$(docker run --rm -v ${GITHUB_WORKSPACE}/semgrep-rules:/src returntocorp/semgrep:${SEMGREP_OLD_VERSION} semgrep --test --test-ignore-todo /src || true)"
+        TESTSUITE_OUTPUT="$(docker run --rm -v ${GITHUB_WORKSPACE}/opengrep-rules:/src opengrep/opengrep:${SEMGREP_OLD_VERSION} semgrep --test --test-ignore-todo /src || true)"
         echo "=== Testsuite output ==="
         echo "${TESTSUITE_OUTPUT}"
         echo "========================"
@@ -69,7 +70,7 @@ jobs:
           done
         fi
         if (( ${#PR_FAILURES[@]} != 0 )) ; then
-          echo "The following test(s) failed with Semgrep v${SEMGREP_OLD_VERSION} are caused by this PR:"
+          echo "The following test(s) failed with Opengrep v${SEMGREP_OLD_VERSION} are caused by this PR:"
           for i in "${PR_FAILURES[@]}" ; do
             echo $i
           done
